### ISSUE TITLE
HTML Templates

### ISSUE THREAD

**Issue by LeafHacker** [ImpactDevelopment/ImpactServer#2]
Split index.html into chunks that are assembled with an epic template meme. Hopefully this'll make things a bit more maintainable and be a step towards going multi-page and/or dynamic content on pages

**Comment by leijurv** [comment]
this is small brain; big brain is a react single page site that's on / and uses # for pages

**Comment by LeafHacker** [comment]
[Website 2.0](/ImpactDevelopment/Website)
