### ISSUE TITLE
Put Discord ID under DiscordTag in accounts dashboard

### ISSUE THREAD

**Issue by ricoip** [ImpactDevelopment/ImpactServer#36]
Minor enhancement - Not useful for anything to be honest, just wanted it to look better.
But you've already shown the Minecraft UUID so why not do the Discord one too
Oh and also fix the discordtag so the name and discriminator don't have space in between.
mockup:
![image](https://user-images.githubusercontent.com/32032824/77138591-9599ea00-6aad-11ea-9c18-9758fff3b574.png)

**Comment by LeafHacker** [comment]
I hadn't included the discord id because (unlike minecraft's id) you can uniquely identify a discord account without it (using the discriminator). That and Discord IDs are normally only accessible if you enable "Developer Mode" in your discord client. But there's no harm in showing it I guess.
