### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by mwahaha9** [ImpactDevelopment/ImpactServer#51]
1, just a very general idea, add the ability to code custom impact plugins / hacks? that would be cool

2. for anarchy servers with 32k's, auto totem takes enough time to switch stacks/totems that you die between them, maybe add other hand support and auto switch before that or somthing lol idk thx

**Comment by berrely** [comment]
Wrong place

**Comment by CesiumCs** [comment]
and pretty sure this would be a duplicate if it were on the right repo

**Comment by berrely** [comment]
> 1, just a very general idea, add the ability to code custom impact plugins / hacks? that would be cool
> 
> 1. for anarchy servers with 32k's, auto totem takes enough time to switch stacks/totems that you die between them, maybe add other hand support and auto switch before that or somthing lol idk thx

please close this
