### ISSUE TITLE
ReferenceError: donate is not defined

### ISSUE THREAD

**Issue by Hexdigest123** [ImpactDevelopment/ImpactServer#59]
When you try to donate something, this appears every time

**Comment by CesiumCs** [comment]
did you try refreshing your browser without the cache? ctrl+shift+r

**Comment by Hexdigest123** [comment]
i tried but it didn't work. Actually idk why but now it works fine.

Am So., 17. Jan. 2021 um 13:49 Uhr schrieb Christian <
notifications@github.com>:
