### ISSUE TITLE
General donator improvements

### ISSUE THREAD

**Issue by ScanmanTM** [ImpactDevelopment/ImpactServer#6]
I think there could be some improvements to the text to stop making people ask question in #help.

**Before making the payment**, ensure your **Minecraft username or uuid** & **discord username#XXX** is included in the PayPal note **to receive the rewards**. The payment can take up to 72 hours to process then afterwards you will receive your rewards.

To receive the nightly builds you **must be in the Discord server** & **specified your discord name** in the PayPal note. After you have been given the Discord donator role a channel called **#donator-info** will appear with all the necessary information.

Furthermore, when the user clicks on the PayPal button a confirmation should pop-up as well confirming they know what to include.
https://stackoverflow.com/questions/10462839/how-to-display-a-confirmation-dialog-when-clicking-an-a-link?rq=1

**Comment by LeafHacker** [comment]
I think this is mostly resolved now that donation/registration is automated.
