### ISSUE TITLE
discord widget not loading

### ISSUE THREAD

**Issue by developomp** [ImpactDevelopment/ImpactServer#70]
Discord widget in the main page is not loading the members list.

**Comment by CesiumCs** [comment]
because [there is none](https://github.com/ImpactDevelopment/ImpactServer/commit/73a41385c8c9ae4aae4dce56ae8539ed492c075a)

**Comment by developomp** [comment]
well this is awkward
![awkward](https://user-images.githubusercontent.com/40858122/111858493-f8ea8080-897c-11eb-86d6-4a556b9a7582.png)

**Comment by CesiumCs** [comment]
"there is none" meaning no more discord

**Comment by developomp** [comment]
I get that you're tired by people with no programming knowledge whatsoever but please, at least take few seconds reading and understanding the issue. especially if someone thinks you're still wrong after you provide a "evidence". Instead, you replied with a condescending `"there is none" meaning no more discord` as if I'm a 9 year old smooth brain. Not all people don't know what they're talking about @CesiumCs.
I said the problem was in the main page which means you need to take a look at `index.html` instead of some other page.
The part of the code responsible for this is [right here](https://github.com/ImpactDevelopment/ImpactServer/blob/8a2473209860caf0f035d7218c51aa21cc3b1637/static/index.html#L324). I think some discord admin messed it up.

**Comment by developomp** [comment]
I tried to be as polite as possible, but I'm still pissed ngl. Please try to fix your attitude next time.

**Comment by CesiumCs** [comment]
the discord server was terminated and there is no more discord server for the widget to point to

we're *hoping* this is temporary and we can just leave the widget there and itll work again when the server gets reinstated but until then it's just gonna show what you see

**Comment by developomp** [comment]
I see. Thank you for your explanation.
To sum things up, discord server has been deleted, but this is hopefully a temporary thing so the widget hasn't been removed yet.
