### ISSUE TITLE
sorts roles in place

### ISSUE THREAD

**Issue by leijurv** [ImpactDevelopment/ImpactServer#8]
https://github.com/ImpactDevelopment/ImpactServer/blob/master/src/api/v1/minecraft.go#L191

this does **not** copy the slice, it pulls a java and only makes a reference, this is sorting the roles for everyone

**Comment by LeafHacker** [comment]
Your line number is out of date, and the archive link is broken xD

**Comment by LeafHacker** [comment]
This was fixed in e1a81d06e21ea1e6fc3f7f4ee823ca0a4ae4ae1c
